context:
  version: "2.23.1"

package:
  name: qunit
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/qunit/-/qunit-${{ version }}.tgz
  sha256: bfc200813770800cede0313c5890fab558444ec54472c0bfa9c5930ff8e282c5

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - qunit --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: The powerful, easy-to-use testing framework.
  homepage: https://github.com/qunitjs/qunit
  repository: https://github.com/qunitjs/qunit

extra:
  recipe-maintainers:
    - danielnachun
