context:
  version: "2.24.2"

package:
  name: qunit
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/qunit/-/qunit-${{ version }}.tgz
  sha256: 0bb099b1f142144e552e15d3d7025d5ec8a87773fa38ba4415b5d5e5bfe1d667

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - qunit --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: The powerful, easy-to-use testing framework.
  homepage: https://github.com/qunitjs/qunit
  repository: https://github.com/qunitjs/qunit

extra:
  recipe-maintainers:
    - danielnachun
