context:
  version: "2.24.1"

package:
  name: qunit
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/qunit/-/qunit-${{ version }}.tgz
  sha256: cca640e305250ee97cf9bb1cdc5b8d496bbf3139d640d5ad21512545f44c9987

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - qunit --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: The powerful, easy-to-use testing framework.
  homepage: https://github.com/qunitjs/qunit
  repository: https://github.com/qunitjs/qunit

extra:
  recipe-maintainers:
    - danielnachun
